/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author yusuf.dur
 */
public class AppScreen extends javax.swing.JFrame {

    /**
     * Creates new form AppScreen
     */
    Client client;
    String userName;
    NameScreen nameScreen;
    DefaultListModel roomsListModel;
    DefaultListModel usersListModel;
    JList<String> r = new JList<>();
    JList<String> u = new JList<>();
    
    ArrayList<RoomScreen> roomsForClient;

    public AppScreen(Client client1, String userName) throws IOException, InterruptedException {
        initComponents();
        setLocationRelativeTo(null);
        this.client = client1;
        this.userName = userName;

        // set list models
        roomsListModel = new DefaultListModel();
        usersListModel = new DefaultListModel();
        lst_rooms.setModel(roomsListModel);
        lst_users.setModel(usersListModel);
        r = lst_rooms;
        u = lst_users;
        roomsForClient = new ArrayList<>();

        // normal operations 
//        this.client.SendMessage(("U_" + userName));  // send username 
        lbl_welcome.setText("Welcome " + userName);
        
        
        // add default chat room by hand 
        roomsListModel.addElement("ChatRoom1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_welcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_rooms = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_users = new javax.swing.JList<>();
        lbl_users = new javax.swing.JLabel();
        lbl_rooms = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_joinRoom = new javax.swing.JButton();
        txt_roomNameToCreate = new javax.swing.JTextField();
        btn_createRoom = new javax.swing.JButton();
        btn_startChat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_roomNameError = new javax.swing.JLabel();
        lbl_selectionError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbl_welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(0, 0, 255));
        lbl_welcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lst_rooms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lst_roomsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lst_rooms);

        lst_users.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lst_usersMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(lst_users);

        lbl_users.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_users.setText("Users");

        lbl_rooms.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_rooms.setText("Rooms");

        jLabel3.setText("You can choose room to join or send private message to the other users");

        btn_joinRoom.setText("Join Room");
        btn_joinRoom.setEnabled(false);
        btn_joinRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_joinRoomActionPerformed(evt);
            }
        });

        txt_roomNameToCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_roomNameToCreateMouseClicked(evt);
            }
        });

        btn_createRoom.setText("Create Room");
        btn_createRoom.setEnabled(false);
        btn_createRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createRoomActionPerformed(evt);
            }
        });

        btn_startChat.setText("Create Private Room");
        btn_startChat.setEnabled(false);
        btn_startChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startChatActionPerformed(evt);
            }
        });

        jSeparator1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator1MouseClicked(evt);
            }
        });

        lbl_roomNameError.setForeground(new java.awt.Color(255, 0, 0));

        lbl_selectionError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_users, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_roomNameToCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(btn_joinRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_createRoom)
                                    .addComponent(lbl_roomNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_startChat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_selectionError, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(lbl_selectionError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_roomNameToCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_roomNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_createRoom)
                                        .addGap(21, 21, 21)
                                        .addComponent(btn_joinRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lbl_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lbl_users, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_startChat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            // TODO add your handling code here:
            this.client.SendMessage("Quit");
            this.client.Stop();
        } catch (InterruptedException ex) {
            System.out.println("gapanırkene hata veriyor gardaaaşşş");
        } catch (IOException ex) {
            Logger.getLogger(AppScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btn_createRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createRoomActionPerformed
        if (txt_roomNameToCreate.getText().isBlank()) {
            lbl_roomNameError.setText("Enter a room name to create");
            return;
        }
        try {
            client.SendMessage("r" + txt_roomNameToCreate.getText());               // create room message to server 
            Thread.sleep(50);
        } catch (IOException ex) {
            Logger.getLogger(AppScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(AppScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_roomNameToCreate.setText("");
        lbl_roomNameError.setText("");
    }//GEN-LAST:event_btn_createRoomActionPerformed

    private void btn_joinRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_joinRoomActionPerformed
        // TODO add your handling code here:
        lst_rooms.setSelectedIndex(-1);
        lst_rooms.setSelectionBackground(Color.WHITE);
        btn_joinRoom.setEnabled(false);

        // server codes ....
        lbl_selectionError.setText("");
        if (lst_rooms.getSelectedIndex() == -1) {
            lbl_selectionError.setText("Please select a room to join");
        } else {

            // access room and chat 
            try {
                RoomScreen rScreen = new RoomScreen(this.client, userName);
                rScreen.setVisible(true);
                rScreen.roomName.setText(lst_rooms.getSelectedValue());
                rScreen.name = lst_rooms.getSelectedValue();

                roomsForClient.add(rScreen);
                
                Thread.sleep(100);
                // I joined the room message 
                this.client.SendMessage("J" + rScreen.name);
            } catch (IOException ex) {
                Logger.getLogger(AppScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(AppScreen.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_btn_joinRoomActionPerformed

    private void btn_startChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startChatActionPerformed
        // TODO add your handling code here:
        lst_users.setSelectedIndex(-1);
        lst_users.setSelectionBackground(Color.WHITE);
        btn_startChat.setEnabled(false);

        // server codes ....
        
        
    }//GEN-LAST:event_btn_startChatActionPerformed

    private void lst_roomsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_roomsMousePressed
        // TODO add your handling code here:
        lst_rooms.setSelectionBackground(new Color(153, 204, 255));
        lst_rooms.setSelectionForeground(Color.BLACK);
        lst_users.setSelectedIndex(-1);
        lst_users.setSelectionBackground(Color.WHITE);

        btn_joinRoom.setEnabled(true);
        btn_startChat.setEnabled(false);
        // disable create button
        btn_createRoom.setEnabled(false);
        txt_roomNameToCreate.revalidate();
    }//GEN-LAST:event_lst_roomsMousePressed

    private void lst_usersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_usersMousePressed
        // TODO add your handling code here:
        lst_users.setSelectionBackground(new Color(153, 204, 255));
        lst_users.setSelectionForeground(Color.BLACK);
        lst_rooms.setSelectedIndex(-1);
        lst_rooms.setSelectionBackground(Color.WHITE);

        btn_startChat.setEnabled(true);
        btn_joinRoom.setEnabled(false);
        // disable create button
        btn_createRoom.setEnabled(false);
        txt_roomNameToCreate.setText("");
        lbl_roomNameError.setText("");
    }//GEN-LAST:event_lst_usersMousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        lst_rooms.setSelectedIndex(-1);
        lst_rooms.setSelectionBackground(Color.WHITE);
        lst_users.setSelectedIndex(-1);
        lst_users.setSelectionBackground(Color.WHITE);
        btn_startChat.setEnabled(false);
        btn_joinRoom.setEnabled(false);
        // disable create button
        btn_createRoom.setEnabled(false);
        txt_roomNameToCreate.setText("");
        lbl_roomNameError.setText("");
    }//GEN-LAST:event_formMouseClicked

    private void jSeparator1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator1MouseClicked
        // TODO add your handling code here:
        lst_rooms.setSelectedIndex(-1);
        lst_rooms.setSelectionBackground(Color.WHITE);
        lst_users.setSelectedIndex(-1);
        lst_users.setSelectionBackground(Color.WHITE);
        btn_startChat.setEnabled(false);
        btn_joinRoom.setEnabled(false);
        // disable create button
        btn_createRoom.setEnabled(false);
        txt_roomNameToCreate.setText("");
        lbl_roomNameError.setText("");
    }//GEN-LAST:event_jSeparator1MouseClicked

    private void txt_roomNameToCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_roomNameToCreateMouseClicked
        // TODO add your handling code here:
        lst_rooms.setSelectedIndex(-1);
        lst_rooms.setSelectionBackground(Color.WHITE);
        lst_users.setSelectedIndex(-1);
        lst_users.setSelectionBackground(Color.WHITE);
        btn_startChat.setEnabled(false);
        btn_joinRoom.setEnabled(false);

        // enable create button
        btn_createRoom.setEnabled(true);
        txt_roomNameToCreate.setText("");
        lbl_roomNameError.setText("");
    }//GEN-LAST:event_txt_roomNameToCreateMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AppScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createRoom;
    private javax.swing.JButton btn_joinRoom;
    private javax.swing.JButton btn_startChat;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_roomNameError;
    private javax.swing.JLabel lbl_rooms;
    private javax.swing.JLabel lbl_selectionError;
    private javax.swing.JLabel lbl_users;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JList<String> lst_rooms;
    private javax.swing.JList<String> lst_users;
    private javax.swing.JTextField txt_roomNameToCreate;
    // End of variables declaration//GEN-END:variables
}
